### ISSUE TITLE
Hey!!

### ISSUE THREAD

**Issue by jwbaldwin** [jfpedroza/neotest-elixir#1]
Hey! I just started looking into the Neotest library and was about to start working on an elixir adapter for it. Figured I'd do a search and found you had just begun one!

I'd love to help out, what all is left/is there a list of things you have left to finish?

**Comment by jfpedroza** [comment]
Hey! Thanks for reaching out.

The adapter is currently working, you can execute the different types (single test, file, etc.) and see the result and the output, but there are many things to improve.

From the top of my head:

* Store output in temp files directly from the ExUnit formatter
* Remove the JSON library dependency by using a simpler format
* Handle dynamic tests like when you have for a loop that generates tests
* Show error in line with diagnostics
* Allow other formatters (I use ExUnitNotifier, and it doesn't work because I override the formatters)
* Probably more

I will make a TODO list in the README tonight
